---
name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: rikorose/gcc-cmake:gcc-10
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=1
      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - uses: actions/upload-artifact@v3
        with:
          name: compilation_database
          path: build/compile_commands.json
  clang-tidy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: compilation_database
          path: ${{github.workspace}}/compile_commands.json
      - name: Run clang-tidy
        run: |
         ls /usr/bin/clang*
         ls /usr/bin/run*
         run-clang-tidy-14
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - run: |
         git ls-files '*.hpp' '.cpp' | xargs clang-format-14 -i --style=file
         git diff --exit-code --stat
