---
name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'true'
      - name: Build&Test
        run: ./scripts/run_unit.sh
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "build/junit/reports/*.xml"
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'true'
      - name: Fetch gcovr
        run: pip3 install gcovr
      - name: Generate coverage
        run: ./scripts/gen_coverage.sh
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage.xml
          name: codecov-elphi
          fail_ci_if_error: true
          verbose: true
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'true'
      - name: Run clang-tidy
        run: scripts/run_clang_tidy.sh
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
         ./scripts/format_codebase.sh
         # Reformatting should have made no changes.
         git diff --exit-code --stat
