---
name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: rikorose/gcc-cmake:gcc-10
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=1
      - name: Build
        run: |
          cmake --build build --config ${{env.BUILD_TYPE}}
          cat ${{github.workspace}}
          cat .
          cat build
      - uses: actions/upload-artifact@v3
        with:
          name: compilation_database
          path: build/compile_commands.json
  clang-tidy:
    runs-on: ubuntu-latest
    container: "xianpengshen/clang-tools:14"
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: compilation_database
          path: ${{github.workspace}}/compile_commands.json
      - name: Run clang-tidy
        run: run-clang-tidy
  clang-format:
    runs-on: ubuntu-latest
    container: mikedld/clang-format:14-debian
    steps:
      - run: |
         sudo apt-get install git
         git ls-files '*.hpp' '.cpp' | xargs clang-format -i --style=file
         git diff --exit-code --stat
